version: 2.1
orbs:
  aws-cli: circleci/aws-cli@1.4.1
environment: &environment
  STACK_NAME: "ci-stack-${CIRCLE_WORKFLOW_ID}"

jobs:
  create_infrastructure:
    executor: aws-cli/default
    environment:
      STACK_NAME: "ci-stack-${CIRCLE_WORKFLOW_ID}"
    steps:
      - checkout
      - aws-cli/install
      - run: ./.circleci/determine-env-color.sh | tee env-color.txt
      - run: ./.circleci/deploy-stack.sh "${STACK_NAME}" "${CIRCLE_WORKFLOW_ID}" "$(cat ./env-color.txt)"
      - run: ./.circleci/create-inventory.sh "${CIRCLE_WORKFLOW_ID}"
      - save_cache:
          key: "inventory-{{ .Environment.CIRCLE_WORKFLOW_ID }}"
          paths: [ "server-inventory.txt" ]
  deploy_app:
    docker:
      - image: circleci/python
    environment:
      STACK_NAME: "ci-stack-${CIRCLE_WORKFLOW_ID}"
    steps:
      - checkout
      - restore_cache:
          keys: [ "inventory-{{ .Environment.CIRCLE_WORKFLOW_ID }}" ]
      - add_ssh_keys:
          fingerprints: [ "df:67:9a:d9:1d:8e:44:b7:38:da:68:6b:b3:1c:4d:c0" ]
      - restore_cache:
          keys: [ 'pip-packages-v2-{{ checksum "deploy/requirements.txt" }}' ]
      - run: ./.circleci/install-ansible.sh
      - save_cache:
          key: pip-packages-v2-{{ checksum "deploy/requirements.txt" }}
          paths:
            - ".venv"
            - "/usr/local/lib/python3.6/site-packages"
      - run: ./.circleci/deploy-app.sh
  smoke_test_app:
    environment:
      STACK_NAME: "ci-stack-${CIRCLE_WORKFLOW_ID}"
    docker:
      - image: circleci/ruby
    steps:
      - checkout
      - run: ./.circleci/smoke-test.rb
      - run:
          command: ./.circleci/delete-stack.sh "${STACK_NAME}"
          when: on_fail
  reroute_blue_green:
    executor: aws-cli/default
    environment:
      STACK_NAME: "ci-stack-${CIRCLE_WORKFLOW_ID}"
    docker:
    steps:
      - checkout
      - aws-cli/install
      - run: echo "REROUTING!"
  cleanup_previous_env:
    executor: aws-cli/default
    environment:
      STACK_NAME: "ci-stack-${CIRCLE_WORKFLOW_ID}"
    docker:
    steps:
      - checkout
      - aws-cli/install
      - run:
          command: ./.circleci/delete-previous-stack.sh
workflows:
  version: 2
  deploy:
    jobs:
      - create_infrastructure
      - deploy_app:
          requires: 
            - create_infrastructure
      - smoke_test_app:
          requires: 
            - deploy_app
      - reroute_blue_green:
          requires: 
            - smoke_test_app
      - cleanup_previous_env:
          requires: 
            - reroute_blue_green
