version: 2.1
jobs:
  create_infrastructure:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run: ./.circleci/deploy-stack.sh "ci-stack" "${CIRCLE_BUILD_NUM}"
      - run: ./.circleci/create-inventory.sh "${CIRCLE_BUILD_NUM}"
      - save_cache:
          key: [ "inventory-{{ .BuildNum }}" ]
          paths: [ "server-inventory.txt" ]
  deploy_app:
    docker:
      - image: circleci/python
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints: [ "df:67:9a:d9:1d:8e:44:b7:38:da:68:6b:b3:1c:4d:c0" ]
      - run: ./.circleci/deploy-app.sh
workflows:
  version: 2
  deploy:
    jobs:
      - create_infrastructure
      - deploy_app:
          requires: 
            - create_infrastructure

