version: 2.1
jobs:
  create_infrastructure:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run: |
          STACK_NAME=ci-stack
          aws cloudformation create-stack --stack-name=$STACK_NAME --template-body=file://infra/servers.yml
          aws cloudformation wait stack-create-complete --stack-name=$STACK_NAME
workflows:
  version: 2
  deploy:
    jobs:
      - create_infrastructure

