---
- name: Install ruby
  become: true
  apt:
    update_cache: yes
    state: latest
    package: [ ruby, git ]
- name: Install app
  shell: git clone https://github.com/dugancathal/udacity-cloud-devops--cicd-playground server
- name: Install dependencies
  become: true
  shell: cd server/app && gem install bundler && bundle check || bundle install
- name: Start server
  shell: cd server/app && bundle exec rackup -D -o 0.0.0.0 -p 9292
